# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: telemetry.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'telemetry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftelemetry.proto\x12\x07phalanx\"\xb2\x01\n\rTargetPayload\x12\x11\n\tsystem_id\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x04\x12\x10\n\x08latitude\x18\x03 \x01(\x01\x12\x11\n\tlongitude\x18\x04 \x01(\x01\x12\x17\n\x0f\x61ltitude_meters\x18\x05 \x01(\x01\x12\x16\n\x0evelocity_knots\x18\x06 \x01(\x02\x12%\n\x06\x64omain\x18\x07 \x01(\x0e\x32\x15.phalanx.ThreatDomain\"M\n\x11IngestionResponse\x12\x1b\n\x13status_acknowledged\x18\x01 \x01(\x08\x12\x1b\n\x13\x61\x63tive_target_count\x18\x02 \x01(\r*R\n\x0cThreatDomain\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x07\n\x03\x41IR\x10\x01\x12\x08\n\x04LAND\x10\x02\x12\x0c\n\x08MARITIME\x10\x03\x12\t\n\x05SPACE\x10\x04\x12\t\n\x05\x43YBER\x10\x05\x32V\n\x0fTelemetryStream\x12\x43\n\rStreamTargets\x12\x16.phalanx.TargetPayload\x1a\x1a.phalanx.IngestionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'telemetry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_THREATDOMAIN']._serialized_start=288
  _globals['_THREATDOMAIN']._serialized_end=370
  _globals['_TARGETPAYLOAD']._serialized_start=29
  _globals['_TARGETPAYLOAD']._serialized_end=207
  _globals['_INGESTIONRESPONSE']._serialized_start=209
  _globals['_INGESTIONRESPONSE']._serialized_end=286
  _globals['_TELEMETRYSTREAM']._serialized_start=372
  _globals['_TELEMETRYSTREAM']._serialized_end=458
# @@protoc_insertion_point(module_scope)
